### ISSUE TITLE
Enlaces a categos.php en varios archivos

### ISSUE THREAD

**Issue by mondarse** [bitcero/works#1]
Por lo que puedo ver en el código de work 2.2.0.8 se ha cambiado el nombre del archivo que gestiona las categorías en el lado del administrador. Creo que antes el nombre era "categos.php" y se ha renombrado a categories.php
Usando el módulo recién instalado he intentado crear una categoría rápida y me ha dado un error:
**" requested URL /modules/works/admin/categos.php "**

Al revisar el código del modulo con un buscador de texto que encontrado que en algunos archivos php se hace referencia a _categories.php_ y en otras a _categos.php_. Supongo que habrá sido un descuido al actualizar el cambio en los scripts del módulo.

Concretamente he encontrado el error en estos archivos:
**admin/categories.php**

``` html
*Línea 2:* // $Id: categos.php 618 2011-03-04 05:41:51Z i.bitcero $
```

**include/widgets.php**

``` html
Línea 19: <form name="frm_categos" id="frm-categos" method="post" action="categos.php">
```

Espero que estas líneas te hayan servido de ayuda.

MonDarSE

**Comment by bitcero** [comment]
Yes! very helpful. Thanks!!

**Comment by bitcero** [comment]
Fixed! Will be released soon
