### ISSUE TITLE
Error on module admin home

### ISSUE THREAD

**Issue by angelorocha** [bitcero/works#2]
Fatal error: Class 'Works_Functions' not found in ...

PHP 5.4
XOOPS 2.5.7
rmcommon 2.2.9.6

**Comment by bitcero** [comment]
Ok... verifying

**Comment by bitcero** [comment]
I was unable to reproduce this error. If this is a new installation verify that works and rmcommon exists in file `xoops_data/caches/xoops_cache/xoops_..._system_modules_active.php`, otherwise provide a little more details.

**Comment by angelorocha** [comment]
I'm trying to use the theme eternial, and also shows the error:

Fatal error: Class 'Works_Functions' not found in 
/themes/ethernial/assemble/plugins/helper.class.php on line 41
