### ISSUE TITLE
Barra de navegación no aparece

### ISSUE THREAD

**Issue by ryuaka** [bitcero/works#4]
En la página principal del módulo; si tengo 16 proyectos y puse que en la página principal se muestren 8 proyectos y en la página 2 se muestren otros 8, no se puede debido a que la barra de navegación del módulo no aparece por ningún lado.

Estoy usando:

Common Utilities 2.3.2.5
Professional Works 2.2.1.8
XOOPS 2.5.7.2

**Comment by bitcero** [comment]
Verificando...
